2 create header
schule4-0/planets pull request #30
Opened 2024-05-14 13:18 UTC by mastoeppler

2024-05-14 13:26 UTC, SebastianMaier03 requested changes
![grafik](https://github.com/schule4-0/planets/assets/115489257/c3a96245-6e46-4e1b-842a-6374905894c3)
The wrong header is implemented here.
Only use 1 header file that checks internally which style should be displayed.

2024-05-14 13:29 UTC, DorinaSobiecki requested changes

2024-05-14 13:29 UTC, DorinaSobiecki commented on app/components/header/HeaderMain.tsx
> +            <div className="flex items-center">
This flex box is unnecessary, remove the div and change the justify in the div above.

2024-05-14 18:12 UTC, DorinaSobiecki requested changes
At the moment there is a blue line at the bottom of the header, please fix that as well.
<img width="958" alt="Screenshot 2024-05-14 200758" src="https://github.com/schule4-0/planets/assets/115489365/3070024d-8255-4db6-9184-caf1e8304dec">

2024-05-14 18:12 UTC, DorinaSobiecki commented on app/components/header/HeaderSubpage.tsx
> +        <header className="flex justify-between items-center bg-[#000582] p-4 text-white relative">
bg-[#000582] Please take a look at the CSS name convention which we defined
Is relative needed here?

2024-05-14 18:12 UTC, DorinaSobiecki commented on app/components/header/HeaderMain.tsx
> +        <header className="flex justify-start items-center p-4 text-white relative bg-cover text-2xl font-bold" style={{ backgroundImage: 'url(/images/headerbg.svg)', fontFamily: 'Agency FB' }}>
Is relative needed here?

2024-05-15 07:43 UTC, DorinaSobiecki approved these changes
LGTM ![](https://media1.giphy.com/media/jRwKzj28kaAxbfH5fC/200.webp?cid=790b7611g6ex55bg8e4ah8ybh2q0jbskrbe71nnojlc2qlhp&ep=v1_gifs_search&rid=200.webp&ct=g)

2024-05-15 13:14 UTC, merged