25 create first dialog page
schule4-0/planets pull request #58
Opened 2024-05-30 15:17 UTC by mastoeppler

2024-05-30 15:26 UTC, DorinaSobiecki commented on public/data/dialog.json
> +    {
It should be one .json per conversation

2024-05-30 15:30 UTC, DorinaSobiecki commented on app/components/speechBubble/speechBubble.tsx
> +    <div className={`speech-bubble ${direction}`} style={bubbleStyles}>
As you already defined a CSS class for the direction the upper bubbleStyles can be in, these CSS classes

2024-05-30 15:35 UTC, DorinaSobiecki commented on pages/dialog.tsx
> +        console.log('Story is finished');
Remove log

2024-05-30 15:36 UTC, DorinaSobiecki commented on pages/dialog.tsx
> +      console.log('Wrong answer');
remove log

2024-05-30 15:38 UTC, DorinaSobiecki commented on pages/dialog.tsx
> +        actionButton={<ActionButton onClick={handleNext} />}
Should be placed inside the layout

2024-05-30 15:39 UTC, DorinaSobiecki commented on pages/dialog.tsx
Outsource the logic into the layout so we don't have to repeat the logic for every conversation when we use separated JSONs

2024-05-30 15:41 UTC, DorinaSobiecki commented on public/data/dialog.json
Please rename folder to "dialog"

2024-05-30 15:42 UTC, DorinaSobiecki requested changes
Take a look at my comments

2024-06-04 10:01 UTC, SebastianMaier03 reviewed
Are there any new Uncommited changes or Updates?

2024-06-04 10:01 UTC, SebastianMaier03 commented on pages/dialog.tsx
> +  }, []);
Adapt Logic and fix dilaog so the character get loadet on empty storage

2024-06-04 10:27 UTC, SebastianMaier03 requested changes
Remove Code that breaks default character loading.
Look at Figma and implement the hint and fix css.
As seen in Figma Wrong answer shoul change color to a different red after the hint was displayed.

2024-06-04 13:27 UTC, mastoeppler commented
Still to do Hint and Question Design

2024-06-10 09:34 UTC, mastoeppler commented
please check if the questions and characters are displayed correctly

2024-06-10 18:20 UTC, DorinaSobiecki requested changes
The speech bubbles are still quite high when there is less text in them.

The image is rendered very small

After a wrong answer to a question, a hit is displayed, after selecting the correct answer, the hint disappears and the question is displayed again for about 1sec before the dialog continues, please fix it so that after a hint is displayed and the correct answer is selected, the dialog continues without the question displayed again.

2024-06-11 12:19 UTC, mastoeppler commented
I have revised it, please check it again

2024-06-11 12:31 UTC, SebastianMaier03 requested changes
![grafik](https://github.com/schule4-0/planets/assets/115489257/bc2602ab-0def-4cbd-a898-8742d6eb5b77)

Speach bubble still so far on top, Img size should be dynamic , and take a look at figma

2024-06-12 07:31 UTC, merged